import { ClassRoom } from '../types';

export const INITIAL_CLASSES: ClassRoom[] = [
  {
    id: 'class-7a1',
    name: '7A1',
    subject: 'Toán học',
    academicYear: '2026-2027',
    createdAt: '2026-08-31T00:00:00.000Z',
    students: [
      { id: '7a1-01', name: 'Nguyễn Văn An', callCount: 0, gender: 'nam', studentCode: 'HS7A1-01' },
      { id: '7a1-02', name: 'Trần Thị Bình', callCount: 1, gender: 'nu', studentCode: 'HS7A1-02' },
      { id: '7a1-03', name: 'Lê Văn Chi', callCount: 0, gender: 'nam', studentCode: 'HS7A1-03' },
      { id: '7a1-04', name: 'Phạm Tiến Dũng', callCount: 2, gender: 'nam', studentCode: 'HS7A1-04' },
      { id: '7a1-05', name: 'Hoàng Minh Đức', callCount: 0, gender: 'nam', studentCode: 'HS7A1-05' },
      { id: '7a1-06', name: 'Vũ Thị Hà Giang', callCount: 1, gender: 'nu', studentCode: 'HS7A1-06' },
      { id: '7a1-07', name: 'Đỗ Thị Thu Hương', callCount: 0, gender: 'nu', studentCode: 'HS7A1-07' },
      { id: '7a1-08', name: 'Bùi Gia Huy', callCount: 1, gender: 'nam', studentCode: 'HS7A1-08' },
      { id: '7a1-09', name: 'Dương Khánh Huyền', callCount: 0, gender: 'nu', studentCode: 'HS7A1-09' },
      { id: '7a1-10', name: 'Ngô Quốc Hưng', callCount: 0, gender: 'nam', studentCode: 'HS7A1-10' },
      { id: '7a1-11', name: 'Phan Thảo Linh', callCount: 1, gender: 'nu', studentCode: 'HS7A1-11' },
      { id: '7a1-12', name: 'Lâm Tuấn Kiệt', callCount: 0, gender: 'nam', studentCode: 'HS7A1-12' },
      { id: '7a1-13', name: 'Trịnh Bảo Long', callCount: 2, gender: 'nam', studentCode: 'HS7A1-13' },
      { id: '7a1-14', name: 'Mai Phương Mai', callCount: 0, gender: 'nu', studentCode: 'HS7A1-14' },
      { id: '7a1-15', name: 'Đặng Nhật Minh', callCount: 1, gender: 'nam', studentCode: 'HS7A1-15' },
      { id: '7a1-16', name: 'Lê Ngọc Mỹ Anh', callCount: 0, gender: 'nu', studentCode: 'HS7A1-16' },
      { id: '7a1-17', name: 'Nguyễn Thành Nam', callCount: 0, gender: 'nam', studentCode: 'HS7A1-17' },
      { id: '7a1-18', name: 'Hoàng Bảo Ngọc', callCount: 1, gender: 'nu', studentCode: 'HS7A1-18' },
      { id: '7a1-19', name: 'Vũ Yến Nhi', callCount: 0, gender: 'nu', studentCode: 'HS7A1-19' },
      { id: '7a1-20', name: 'Phạm Hồng Phúc', callCount: 1, gender: 'nam', studentCode: 'HS7A1-20' },
      { id: '7a1-21', name: 'Trần Phú Quý', callCount: 0, gender: 'nam', studentCode: 'HS7A1-21' },
      { id: '7a1-22', name: 'Nguyễn Như Quỳnh', callCount: 0, gender: 'nu', studentCode: 'HS7A1-22' },
      { id: '7a1-23', name: 'Đoàn Minh Sơn', callCount: 1, gender: 'nam', studentCode: 'HS7A1-23' },
      { id: '7a1-24', name: 'Lý Quốc Thắng', callCount: 0, gender: 'nam', studentCode: 'HS7A1-24' },
      { id: '7a1-25', name: 'Vương Thanh Thảo', callCount: 0, gender: 'nu', studentCode: 'HS7A1-25' },
      { id: '7a1-26', name: 'Tạ Minh Triết', callCount: 1, gender: 'nam', studentCode: 'HS7A1-26' },
      { id: '7a1-27', name: 'Hồ Cẩm Tú', callCount: 0, gender: 'nu', studentCode: 'HS7A1-27' },
      { id: '7a1-28', name: 'Đinh Quốc Tuấn', callCount: 0, gender: 'nam', studentCode: 'HS7A1-28' },
      { id: '7a1-29', name: 'Lưu Tường Vy', callCount: 1, gender: 'nu', studentCode: 'HS7A1-29' },
      { id: '7a1-30', name: 'Cao Hải Yến', callCount: 0, gender: 'nu', studentCode: 'HS7A1-30' },
    ],
  },
  {
    id: 'class-7a2',
    name: '7A2',
    subject: 'Ngữ văn',
    academicYear: '2026-2027',
    createdAt: '2026-08-31T00:00:00.000Z',
    students: [
      { id: '7a2-01', name: 'Võ Minh Ánh', callCount: 0, gender: 'nu', studentCode: 'HS7A2-01' },
      { id: '7a2-02', name: 'Đặng Tuấn Anh', callCount: 0, gender: 'nam', studentCode: 'HS7A2-02' },
      { id: '7a2-03', name: 'Bùi Kim Chi', callCount: 1, gender: 'nu', studentCode: 'HS7A2-03' },
      { id: '7a2-04', name: 'Lương Quốc Đạt', callCount: 0, gender: 'nam', studentCode: 'HS7A2-04' },
      { id: '7a2-05', name: 'Thái Mỹ Dung', callCount: 0, gender: 'nu', studentCode: 'HS7A2-05' },
      { id: '7a2-06', name: 'Phan Minh Hải', callCount: 1, gender: 'nam', studentCode: 'HS7A2-06' },
      { id: '7a2-07', name: 'Tạ Thúy Hằng', callCount: 0, gender: 'nu', studentCode: 'HS7A2-07' },
      { id: '7a2-08', name: 'Trịnh Hoàng Long', callCount: 0, gender: 'nam', studentCode: 'HS7A2-08' },
      { id: '7a2-09', name: 'Trần Trúc Mai', callCount: 0, gender: 'nu', studentCode: 'HS7A2-09' },
      { id: '7a2-10', name: 'Nguyễn Trọng Nghĩa', callCount: 1, gender: 'nam', studentCode: 'HS7A2-10' },
      { id: '7a2-11', name: 'Đỗ Quỳnh Nga', callCount: 0, gender: 'nu', studentCode: 'HS7A2-11' },
      { id: '7a2-12', name: 'Chu Đình Phong', callCount: 0, gender: 'nam', studentCode: 'HS7A2-12' },
      { id: '7a2-13', name: 'Hà Hương Thảo', callCount: 0, gender: 'nu', studentCode: 'HS7A2-13' },
      { id: '7a2-14', name: 'Lê Minh Quân', callCount: 2, gender: 'nam', studentCode: 'HS7A2-14' },
      { id: '7a2-15', name: 'Nguyễn Diệp Uyên', callCount: 0, gender: 'nu', studentCode: 'HS7A2-15' },
    ],
  },
  {
    id: 'class-8a1',
    name: '8A1',
    subject: 'Vật lý',
    academicYear: '2026-2027',
    createdAt: '2026-08-31T00:00:00.000Z',
    students: [
      { id: '8a1-01', name: 'Nguyễn Phúc An', callCount: 0, gender: 'nam' },
      { id: '8a1-02', name: 'Lê Gia Bảo', callCount: 0, gender: 'nam' },
      { id: '8a1-03', name: 'Phạm Minh Châu', callCount: 0, gender: 'nu' },
      { id: '8a1-04', name: 'Trần Hải Đăng', callCount: 0, gender: 'nam' },
      { id: '8a1-05', name: 'Vũ Ngọc Hân', callCount: 0, gender: 'nu' },
      { id: '8a1-06', name: 'Hoàng Nhật Huy', callCount: 0, gender: 'nam' },
      { id: '8a1-07', name: 'Đỗ Mai Khanh', callCount: 0, gender: 'nu' },
      { id: '8a1-08', name: 'Bùi Đức Khang', callCount: 0, gender: 'nam' },
      { id: '8a1-09', name: 'Lâm Tuệ Lâm', callCount: 0, gender: 'nu' },
      { id: '8a1-10', name: 'Dương Việt Nam', callCount: 0, gender: 'nam' },
    ],
  },
];
